security:
  oauth2:
    resource:
      token-info-uri: lb://AUTH-SERVER/oauth/check_token
    client:
      client-id: authorization-service
      client-secret: authorization-secret

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans'

spring:
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: authdb
      port: 27017