management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans'
spring:
  data:
    mongodb:
      uri: mongodb://root:strongPassword@localhost:27017/authdb?authSource=admin&retryWrites=true&w=majority