management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans'

spring:
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: authdb
      port: 27017