security:
  oauth2:
    resource:
      token-info-uri: lb://AUTH-SERVER/oauth/check_token
    client:
      client-id: authorization-service
      client-secret: authorization-secret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans'

spring:
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: authdb
      port: 27017