server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: *
        exclude: env,beans
---
spring:
  profiles: dev
  cloud:
    gateway:
      routes:
        - id: products
          uri: http://localhost:8081
          predicates:
            - Path=/products
          filters:
            - TokenRelay=
        - id: authorization
          uri: http://localhost:9191
          predicates:
            - Path=/auth
          filters:
            - TokenRelay=
  main:
    web-application-type: reactive
---
spring:
  profiles: test
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay=
        - SaveSession
      routes:
        - id: authorizations
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - TokenRelay=
        - id: products
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - TokenRelay=
  main:
    web-application-type: reactive
---
spring:
  profiles: prod
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay=
        - SaveSession
      routes:
        - id: authorizations
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - TokenRelay=
        - id: products
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - TokenRelay=
  main:
    web-application-type: reactive