security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: products-service
      client-secret: products-secret

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans'

spring:
  data:
    mongodb:
      uri: mongodb://root:strongPassword@localhost:27017/productsdb?authSource=admin&retryWrites=true&w=majority