security:
  oauth2:
    resource:
      token-info-uri: lb://AUTH-SERVER/oauth/check_token
    client:
      client-id: products-service
      client-secret: products-secret

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans'

spring:
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: products
      port: 27017