security:
  oauth2:
    resource:
      token-info-uri: lb://AUTH-SERVER/oauth/check_token
    client:
      client-id: products-service
      client-secret: products-secret
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2
server:
  port: 8382
management:
  endpoints:
    web:
      exposure:
        include: *
        exclude: env,beans

spring:
  application:
    name: products-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVICE
      enabled: true
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      auto-index-creation: true
      password: strongPassword
      username: root
      database: products
      port: 27017